AppBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        firstName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: last_name
        passwordHash:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: password_hash
    lifecycleCallbacks: {  }
