# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    email_template:
        register :
            subject : "Welcome to our application!"
            template : "Emails/register.email.twig"
            from: "hello@i-take-unconf.com"
        forgot_password :
            subject : "Forgot your password ?"
            template : "Emails/forgot.email.twig"
            from: "news@ideaspace.ml"

services:
    email_manager:
        class:        AppBundle\Service\EmailService
        arguments:
            - '@templating'
            - '@mailer'
            - '%email_template%'



